---
title: "Benjamin PREVOT - Jeedom plugin - Connexoon"
description: "Documentation du plugin permettant de piloter la box Connexoon."
author: "Benjamin PREVOT"
langs: [ fr_FR ]
baseurl: "/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
