---
title: "Benjamin PREVOT - Jeedom plugin - Coonexoon"
description: "Benjamin PREVOT - Jeedom plugin - Coonexoon"
author: "Benjamin PREVOT"
langs:
  - fr_FR
baseurl: "/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
twitter:
  username: benjaminprevot
  card: summary
social:
  name: "Benjamin PREVOT"
  links:
    - https://twitter.com/benjaminprevot
    - https://www.linkedin.com/in/benjaminprevot
    - https://github.com/benjaminprevot
